In [60]:
import pandas as pd
import numpy as np

In [61]:
data=pd.read_csv('Dataset.csv')
data.head(1)

Restaurant ID   Restaurant Name  Country Code         City  \
0        6317637  Le Petit Souffle           162  Makati City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   

                                    Locality  \
0  Century City Mall, Poblacion, Makati City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   

                     Cuisines  ...          Currency Has Table booking  \
0  French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  

[1 rows x 21 columns]

In [62]:
data.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [63]:
data[['Locality','City','Cuisines','Average Cost for two','Aggregate rating','Has Online delivery']]

Locality              City  \
0      Century City Mall, Poblacion, Makati City       Makati City   
1     Little Tokyo, Legaspi Village, Makati City       Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City  Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City  Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City  Mandaluyong City   
...                                          ...               ...   
9546                                    Karak�_y         ��stanbul   
9547                                   Ko��uyolu         ��stanbul   
9548                                 Kuru�_e��me         ��stanbul   
9549                                 Kuru�_e��me         ��stanbul   
9550                                        Moda         ��stanbul   

                              Cuisines  Average Cost for two  \
0           French, Japanese, Desserts                  1100   
1                             Japanese                  1200   
2     Seafood, Asian, Filipino, Indian                  4000   
3                      Japanese, Sushi                  1500   
4                     Japanese, Korean                  1500   
...                                ...                   ...   
9546                           Turkish                    80   
9547   World Cuisine, Patisserie, Cafe                   105   
9548            Italian, World Cuisine                   170   
9549                   Restaurant Cafe                   120   
9550                              Cafe                    55   

      Aggregate rating Has Online delivery  
0                  4.8                  No  
1                  4.5                  No  
2                  4.4                  No  
3                  4.9                  No  
4                  4.8                  No  
...                ...                 ...  
9546               4.1                  No  
9547               4.2                  No  
9548               3.7                  No  
9549               4.0                  No  
9550               4.0                  No  

[9551 rows x 6 columns]

In [64]:
s1=[]
temp=data['Locality'].to_list()
for i in range(len(temp)):
    s=temp[i]
    s=s.split(",")
    s1.append(s[0])
print(s1)
data['New_locality']=s1

['Century City Mall', 'Little Tokyo', 'Edsa Shangri-La', 'SM Megamall', 'SM Megamall', 'SM Megamall', 'SM by the Bay', 'SM by the Bay', 'Sofitel Philippine Plaza Manila', 'Kapitolyo', 'Kapitolyo', 'Kapitolyo', 'UP Town Center', 'Addition Hills', 'Little Baguio', 'Nuvali', 'Solenad 3', 'Tagaytay City', 'BGC Stopover Pavillion', 'Bonifacio Global City', 'SM Aura Premier', 'SM Aura Premier', 'Asa Norte', 'Asa Norte', 'Asa Norte', 'Asa Norte', 'Asa Sul', 'Asa Sul', 'Asa Sul', 'Asa Sul', 'Asa Sul', 'Asa Sul', '�guas Claras', '�guas Claras', '�guas Claras', 'Bras�_lia Shopping', 'Lago Sul', 'ParkShopping', 'Pont��o Lago Sul', 'Setor De Clubes Esportivos Sul', 'Shopping Iguatemi', 'Sudoeste', 'Barra da Tijuca', 'Centro', 'Copacabana', 'Copacabana', 'Copacabana', 'Galeria River', 'G��vea', 'Ipanema', 'Ipanema', 'Ipanema', 'Lagoa', 'Le Monde', 'Leblon', 'Leblon', 'Leme', 'Leme', 'Madureira', 'Santa Teresa', 'Tijuca', 'Urca', 'Bela Vista', 'Bela Vista', 'Consola�_��o', 'Consola�_��o', 'Hotel Uni

In [65]:
data.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes', 'New_locality'],
      dtype='object')

In [66]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
en=le.fit_transform(data['Restaurant Name'])

In [67]:
en

array([3748, 3172, 2896, ..., 3068,  512, 7240])

In [68]:
data['Restaurant name en']=en

In [69]:
data.head(1)

Restaurant ID   Restaurant Name  Country Code         City  \
0        6317637  Le Petit Souffle           162  Makati City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   

                                    Locality  \
0  Century City Mall, Poblacion, Makati City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   

                     Cuisines  ...  Has Online delivery Is delivering now  \
0  French, Japanese, Desserts  ...                   No                No   

  Switch to order menu Price range Aggregate rating Rating color  Rating text  \
0                   No           3              4.8   Dark Green    Excellent   

   Votes       New_locality Restaurant name en  
0    314  Century City Mall               3748  

[1 rows x 23 columns]

In [70]:
x=data[['Aggregate rating','Restaurant name en']]

In [71]:
x

Aggregate rating  Restaurant name en
0                  4.8                3748
1                  4.5                3172
2                  4.4                2896
3                  4.9                4707
4                  4.8                5523
...                ...                 ...
9546               4.1                4443
9547               4.2                1310
9548               3.7                3068
9549               4.0                 512
9550               4.0                7240

[9551 rows x 2 columns]

In [72]:
#using aggregate rating as criteria for recommendation
import numpy as np
avg=np.array(x['Aggregate rating']).reshape(-1,1)
rname=np.array(x['Restaurant name en']).reshape(-1,1)

vec1=np.hstack([avg,rname])

In [73]:
vec1

array([[4.800e+00, 3.748e+03],
       [4.500e+00, 3.172e+03],
       [4.400e+00, 2.896e+03],
       ...,
       [3.700e+00, 3.068e+03],
       [4.000e+00, 5.120e+02],
       [4.000e+00, 7.240e+03]])

In [74]:
#using cosine similarity for getting recommendations
from sklearn.metrics.pairwise import cosine_similarity
sim=cosine_similarity(vec1)
#print(sim)
a=sim[1]
#print(a)
movies_list=sorted(list(enumerate(a)),reverse=True,key=lambda x:x[1])[1:3]
print(movies_list)
for i in movies_list:
    b=i[0]
    print(b)
    c=data.iloc[b,:]
    print(c['Restaurant Name'])

[(2399, 0.999999999999975), (9113, 0.9999999999997531)]
2399
Hoppipola
9113
Hops n Grains


In [75]:
data[data['Restaurant Name']=="Hops n Grains"].values

array([[120519, 'Hops n Grains', 1, 'Panchkula',
        'SCO 358, Sector 9, Panchkula', 'Sector 9',
        'Sector 9, Panchkula', 76.849258, 30.6978586,
        'North Indian, Middle Eastern, Pizza', 2000,
        'Indian Rupees(Rs.)', 'No', 'No', 'No', 'No', 4, 4.2, 'Green',
        'Very Good', 843, 'Sector 9', 2962]], dtype=object)

In [76]:
#using knn for the same criteria
knn.fit(vec1)

NearestNeighbors(metric='cosine', n_neighbors=4)

In [77]:
#giving index value of a particular restaurant as input in item_of_interest
item_of_interest=1
distances, indices = knn.kneighbors(vec1[item_of_interest].reshape(1, -1))
print(indices)

[[   1 2399 9113  426]]


In [78]:
data.iloc[9113,:]

Restaurant ID                                        120519
Restaurant Name                               Hops n Grains
Country Code                                              1
City                                              Panchkula
Address                        SCO 358, Sector 9, Panchkula
Locality                                           Sector 9
Locality Verbose                        Sector 9, Panchkula
Longitude                                         76.849258
Latitude                                          30.697859
Cuisines                North Indian, Middle Eastern, Pizza
Average Cost for two                                   2000
Currency                                 Indian Rupees(Rs.)
Has Table booking                                        No
Has Online delivery                                      No
Is delivering now                                        No
Switch to order menu                                     No
Price range                             

In [79]:
data.iloc[1,:]

Restaurant ID                                                     6304287
Restaurant Name                                          Izakaya Kikufuji
Country Code                                                          162
City                                                          Makati City
Address                 Little Tokyo, 2277 Chino Roces Avenue, Legaspi...
Locality                       Little Tokyo, Legaspi Village, Makati City
Locality Verbose        Little Tokyo, Legaspi Village, Makati City, Ma...
Longitude                                                      121.014101
Latitude                                                        14.553708
Cuisines                                                         Japanese
Average Cost for two                                                 1200
Currency                                                 Botswana Pula(P)
Has Table booking                                                     Yes
Has Online delivery                   

In [80]:
#using KNN for recommendation
#using cuisines,locality and aggregate rating as criteria for recommendation
y=data.iloc[:,:]

In [81]:
y.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes', 'New_locality', 'Restaurant name en'],
      dtype='object')

In [82]:
new_c=le.fit_transform(y['Cuisines'])

In [83]:
le.fit_transform(data['Cuisines'])
new_l=le.fit_transform(y['New_locality'])

In [84]:
rest_id=y['Restaurant ID']

In [85]:
rest_id=np.array(rest_id).reshape(-1,1)
new_c=np.array(new_c).reshape(-1,1)
new_l=np.array(new_l).reshape(-1,1)
price=np.array(y['Aggregate rating']).reshape(-1,1)
vec=np.hstack([rest_id,new_c,new_l,price])
vec

array([[6.317637e+06, 9.200000e+02, 1.670000e+02, 4.800000e+00],
       [6.304287e+06, 1.111000e+03, 5.830000e+02, 4.500000e+00],
       [6.300002e+06, 1.671000e+03, 3.020000e+02, 4.400000e+00],
       ...,
       [5.915807e+06, 1.110000e+03, 5.450000e+02, 3.700000e+00],
       [5.916112e+06, 1.657000e+03, 5.450000e+02, 4.000000e+00],
       [5.927402e+06, 3.310000e+02, 6.590000e+02, 4.000000e+00]])

In [86]:
from sklearn.neighbors import NearestNeighbors
knn=NearestNeighbors(n_neighbors=4,metric='cosine')

In [87]:
knn.fit(vec)

NearestNeighbors(metric='cosine', n_neighbors=4)

In [88]:
#giving index value of a particular restaurant as input in item_of_interest
item_of_interest=20
distances, indices = knn.kneighbors(vec[item_of_interest].reshape(1, -1))

In [89]:
print(indices)

[[  20    7 9327 9494]]


In [90]:
y.iloc[7,:]

Restaurant ID                                                     6301290
Restaurant Name                                                   Vikings
Country Code                                                          162
City                                                           Pasay City
Address                 Building B, By The Bay, Seaside Boulevard, Mal...
Locality                  SM by the Bay, Mall of Asia Complex, Pasay City
Locality Verbose        SM by the Bay, Mall of Asia Complex, Pasay Cit...
Longitude                                                      120.979333
Latitude                                                            14.54
Cuisines                               Seafood, Filipino, Asian, European
Average Cost for two                                                 2000
Currency                                                 Botswana Pula(P)
Has Table booking                                                     Yes
Has Online delivery                   

In [91]:
y.iloc[20,:]

Restaurant ID                                                     6315438
Restaurant Name                                            NIU by Vikings
Country Code                                                          162
City                                                          Taguig City
Address                 Sixth Floor, SM Aura Premier, C5 Road Corner 2...
Locality                SM Aura Premier, Bonifacio Global City, Taguig...
Locality Verbose        SM Aura Premier, Bonifacio Global City, Taguig...
Longitude                                                      121.053725
Latitude                                                        14.545858
Cuisines                       Seafood, American, Mediterranean, Japanese
Average Cost for two                                                 3000
Currency                                                 Botswana Pula(P)
Has Table booking                                                     Yes
Has Online delivery                   